-- Financial Tracker — default categories + starter merchant rules (Phase 1)
-- All of this is editable from the portal.

insert into public.categories (name, icon, color, sort) values
  ('Food & Dining',    'tools-kitchen-2',  '#eb6834', 10),
  ('Groceries',        'shopping-cart',    '#1baf7a', 20),
  ('Clothing',         'shirt',            '#e87ba4', 30),
  ('Shopping',         'shopping-bag',     '#4a3aa7', 40),
  ('Transport',        'car',              '#2a78d6', 50),
  ('Fuel',             'gas-station',      '#b45309', 60),
  ('Utilities & Bills','bolt',             '#eda100', 70),
  ('Rent & Housing',   'home',             '#6d28d9', 80),
  ('Health',           'stethoscope',      '#e34948', 90),
  ('Entertainment',    'device-tv',        '#d55181', 100),
  ('Travel',           'plane',            '#0ea5e9', 110),
  ('Education',        'school',           '#008300', 120),
  ('Personal Care',    'massage',          '#9085e9', 130),
  ('Gifts & Donations','gift',             '#c026d3', 140),
  ('Fees & Charges',   'receipt-2',        '#64748b', 150),
  ('Transfers',        'arrows-exchange',  '#57574f', 160),
  ('Income',           'cash',             '#15803d', 170),
  ('Other',            'dots',             '#898781', 180);

insert into public.merchant_rules (pattern, match_type, category_id)
select v.pattern, 'contains', c.id
from (values
  ('swiggy',        'Food & Dining'),
  ('zomato',        'Food & Dining'),
  ('dominos',       'Food & Dining'),
  ('mcdonald',      'Food & Dining'),
  ('kfc',           'Food & Dining'),
  ('starbucks',     'Food & Dining'),
  ('bigbasket',     'Groceries'),
  ('blinkit',       'Groceries'),
  ('zepto',         'Groceries'),
  ('instamart',     'Groceries'),
  ('dmart',         'Groceries'),
  ('reliance fresh','Groceries'),
  ('myntra',        'Clothing'),
  ('ajio',          'Clothing'),
  ('amazon',        'Shopping'),
  ('flipkart',      'Shopping'),
  ('uber',          'Transport'),
  ('ola',           'Transport'),
  ('rapido',        'Transport'),
  ('redbus',        'Transport'),
  ('hpcl',          'Fuel'),
  ('iocl',          'Fuel'),
  ('bpcl',          'Fuel'),
  ('petrol',        'Fuel'),
  ('jio',           'Utilities & Bills'),
  ('airtel',        'Utilities & Bills'),
  ('vodafone',      'Utilities & Bills'),
  ('bsnl',          'Utilities & Bills'),
  ('electricity',   'Utilities & Bills'),
  ('bescom',        'Utilities & Bills'),
  ('netflix',       'Entertainment'),
  ('spotify',       'Entertainment'),
  ('hotstar',       'Entertainment'),
  ('prime video',   'Entertainment'),
  ('bookmyshow',    'Entertainment'),
  ('irctc',         'Travel'),
  ('makemytrip',    'Travel'),
  ('goibibo',       'Travel'),
  ('indigo',        'Travel'),
  ('oyo',           'Travel'),
  ('apollo',        'Health'),
  ('pharmeasy',     'Health'),
  ('1mg',           'Health'),
  ('netmeds',       'Health'),
  ('medplus',       'Health'),
  ('salary',        'Income')
) as v(pattern, cat)
join public.categories c on c.name = v.cat;
